Metrics/AbcSize:
    Max: 42

Metrics/CyclomaticComplexity:
  Max: 13

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 36
  Exclude:
    - 'lib/lab_manager/provider/vsphere.rb'

Style/ClassLength:
  Exclude:
    - 'lib/lab_manager/provider/vsphere.rb'

Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - 'lib/lab_manager/models/compute.rb'
    - 'lib/lab_manager/models/action.rb'

Style/Documentation:
  Enabled: true
  Exclude:
    - 'config/application.rb'
    - 'db/migrate/20150819122640_create_computes.rb'
    - 'db/migrate/20150909130531_create_actions.rb'
    - 'lib/lab_manager/models.rb'
Style/ExtraSpacing:
  Description: 'Do not use unnecessary spacing.'
  Enabled: false
Style/RedundantSelf:
  Exclude:
    - 'lib/lab_manager/models/action.rb'

Style/SpaceBeforeFirstArg:
  Exclude:
    - 'lib/lab_manager/models/compute.rb'

Style/EachWithObject:
  Enabled: false

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
